name: Deploy to Shardborne site

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: 'Get latest version'
              id: version
              run: echo "id=$(curl -s https://raw.githubusercontent.com/misode/mcmeta/summary/version.txt)" >> $GITHUB_OUTPUT

            - name: Build
              run: |
                  npm install
                  export latest_version="'${{ steps.version.outputs.id }}'"
                  npm run build

            - name: Copy folder content recursively to remote
              uses: appleboy/scp-action@v0.1.7
              with:
                  source: dist
                  target: generator
                  host: ${{ secrets.SSH_HOST }}
                  port: ${{ secrets.SSH_PORT }}
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.SSH_PASSWORD }}
